version: '3.1'

services:
  web:
    build: ./app
    depends_on:
      db
    environment:
      - FLASK_SECRET_KEY=/run/secrets/flask-key
    expose:
      - 5000
  db:
    image: mysql:8
    restart: always
    secrets:
      - db-user
      - db-password
      - db-name
    volumes:
      - app/db:/var/lib/mysql   
    environment:
      PROJECT_DB_USER=/run/secrets/db-user
      PROJECT_DB_PWD=/run/secrets/db-password
      PROJECT_DB_DB=/run/secrets/db-name
    expose:
      - 3306
      - 33060

  proxy:
    build: ./proxy
    restart: always
    ports:
      - 80:80
    depends_on:
      - web

secrets:
  db-user:
    file: db/user.txt
  db-password:
    file: db/password.txt
  db-name:
    file: db/name.txt
  flask-key:
    file: app/key.txt